[package]
name = "example"
version = "0.2.0"
edition = "2024"

[features]
some_feature = []

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
egui = "0.35.0"
egui-wgpu = { version = "0.35.0", features = ["winit"] }
egui-winit = "0.35.0"
pollster = "0.4.0"
winit = "0.30.13"

[build-dependencies]
cargo-crapapp = { path = "..", default-features = false, features = ["windows"] }
