[build]
publisher = "ufnkam"
display_name = "Example App"
packages = ["example"]
features = ["some_feature"]

[windows]
targets = [
    "x86_64-pc-windows-gnu",
]
install_path = "$INSTALLPATH"
files = [
    { source = "Cargo.toml", destination = "Resources/manifests/Cargo.toml" },
    { source = "some_assets", destination = "Resources/some_assets" },
]
associated_files = [
    { path = "$HOMEPATH/Documents/Example App/saves", kind = "directory" },
    { path = "$HOMEPATH/Documents/Example App/eulas", kind = "directory", eula_report = true },
    { path = "$INSTALLPATH/settings.json", kind = "file" },
]
shortcuts = [
    { binary = "first_bin", name = "Example First", directory = "Example App", icon = "build_assets/first.ico" },
    { binary = "second_bin", name = "Example Second", directory = "Example App", icon = "build_assets/second.ico" },
]
eulas = [
    { path = "EULA.txt" },
    { path = "EULA2.txt", required = false },
]
display_icon = "build_assets/icon.ico"
bundle = [ "gui" ]

# [linux]
# targets = [
#     "x86_64-unknown-linux-gnu",
# ]
# files = [
#     { source = "Cargo.toml", destination = "etc/example/Cargo.toml" },
# ]
[macos]
targets = [
    "aarch64-apple-darwin",
]
bundle = "app"
display_icon = "build_assets/icon.icns"
app_binary = "example"
files = [
    { source = "Cargo.toml", destination = "manifests/Cargo.toml" },
    { source = "some_assets", destination = "some_assets" },
]
