[package]
name = "cargo-crapapp"
version = "0.3.0"
edition = "2024"
description = "Cargo subcommand for building CRAP app installers and self-contained app bundles"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/cargo-crapapp"
keywords = ["cargo", "packaging", "bundler", "installer", "desktop"]
categories = [
    "command-line-utilities",
    "development-tools::cargo-plugins",
    "development-tools::build-utils",
]
repository = "https://github.com/ufnkam/crapapp"

[workspace]
members = ["example"]
default-members = ["."]
exclude = ["example/.crapapp_build"]
resolver = "3"

[lib]
name = "libcrapapp"
path = "src/lib.rs"

[[bin]]
name = "cargo-crapapp"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.103"
cargo_metadata = "0.23.1"
clap = { version = "4.5.40", features = ["derive"] }
directories = { version = "6.0.0", optional = true }
flate2 = "1.1.9"
iced = { version = "0.14.0", features = ["image-without-codecs"], optional = true }
image = { version = "0.25.10", default-features = false, features = ["ico", "png"] }
minijinja = "2.12.0"
quick-xml = "0.41.0"
rfd = { version = "0.17.2", optional = true }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.150"
sha1 = "0.10.7"
strum = { version = "0.28.0", features = ["derive"] }
strum_macros = "0.28.0"
toml = "0.8.23"
usvg = { version = "0.47.0", default-features = false }
winresource = { version = "0.1.23", optional = true}
serde-bool = "0.1.4"
msi = "0.10.0"
cab = "0.6.0"
chrono = { version = "0.4.41", default-features = false, features = ["alloc", "clock"] }
uuid = { version = "1.18.1", features = ["v5"] }
rpm = { version = "0.25.1", default-features = false, features = ["payload", "gzip-compression"] }

[features]
default = []
dev = []
cli = ["windows-cli"]
gui = ["windows-gui"]
windows = ["dep:winresource"]
windows-cli = ["windows"]
windows-gui = ["windows", "dep:directories", "dep:iced", "dep:rfd"]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = ["Win32_System_Com", "Win32_UI_Shell"] }
winreg = "0.56.0"
