[package]
name = "cargo-crapapp"
version = "0.2.0"
edition = "2024"
description = "Cargo subcommand for building CRAP app installers and self-contained app bundles"
license = "Apache-2.0"
readme = "README.md"
keywords = ["cargo", "packaging", "bundler", "installer", "desktop"]
categories = [
    "command-line-utilities",
    "development-tools::cargo-plugins",
    "development-tools::build-utils",
]

[workspace]
members = ["example", "packages/cargoapp", "packages/windows-installer"]
exclude = ["example/.crapapp_build"]
resolver = "3"

[lib]
name = "cargo_crapapp"
path = "src/lib.rs"

[[bin]]
name = "cargo-crapapp"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.103"
cargoapp = { version = "0.2.0", path = "packages/cargoapp" }
